# Generated by Django 4.2.1 on 2023-05-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='ToDoList',
        ),
    ]
